spring:
  application:
    name: hytrixconsumer
  redis:
    host: 192.168.136.128
    port: 6379
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.136.128:8761/eureka/,http://192.168.136.129:8761/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1500 //一般配置是大于4000ms
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

#privider:
#  ribbon:
#    NFLoadBalancecerRuleClassName: com.netflix.loadbalancer.RandomRule